// Device Icons — Lucide React (universal) v3.36.0
import React from 'react'
import {
  Camera, Video, Webcam, Eye, ScanEye, Car, Wifi,
  ScanFace, Fingerprint, Lock, Cog,
  Network, Cable, HardDrive, Router,
  Server, BatteryCharging, Battery, Plug, Zap, LayoutGrid, CircuitBoard,
  ShieldAlert, PersonStanding, DoorOpen, ScanLine, Keyboard, Flame, CircleAlert,
  Radio, Signal, Lightbulb, Unplug, GripHorizontal, Siren,
  // Extra icons for the icon bank
  Monitor, Cpu, Mic, Speaker, Bell, Shield, Scan,
  Tv, Power, Activity, Gauge, Globe, Building2,
  Key, Smartphone, Truck, MapPin, Thermometer, Droplets,
  Wind, Volume2, AlertTriangle, Move, SquareStack, Box,
  Hash, ToggleLeft, Compass, Aperture, Focus, Target,
  Megaphone, Waypoints, AudioLines,
  Mouse, Usb, Grid2x2, MonitorSpeaker
} from 'lucide-react'

const ic = (Icon, defaultColor) => (c) => (
  <Icon size={28} color={c || defaultColor} strokeWidth={1.8} />
)

export const ICONS = {
  // CFTV
  cam_dome:    ic(Webcam, '#f59e0b'),
  cam_bullet:  ic(Video, '#f59e0b'),
  cam_ptz:     ic(ScanEye, '#f59e0b'),
  cam_fisheye: ic(Eye, '#f59e0b'),
  cam_lpr:     ic(Car, '#f59e0b'),
  cam_wifi:    ic(Video, '#0ea5e9'),
  // Controle de Acesso
  leitor_facial: ic(ScanFace, '#8b5cf6'),
  controladora:  ic(Fingerprint, '#8b5cf6'),
  fechadura:     ic(Lock, '#8b5cf6'),
  motor:         ic(Cog, '#ea580c'),
  leitor_tag:    ic(Signal, '#8b5cf6'),
  cancela:       ic(Unplug, '#ea580c'),
  // Rede
  sw_poe:    ic(Network, '#2563eb'),
  sw_normal: ic(Cable, '#2563eb'),
  nvr:       ic(HardDrive, '#059669'),
  dvr:       ic(HardDrive, '#d97706'),
  router:    ic(Router, '#059669'),
  ap_wifi:   ic(Wifi, '#2563eb'),
  dio:       ic(CircuitBoard, '#0ea5e9'),
  // Infraestrutura
  rack:            ic(Server, '#6b7280'),
  nobreak:         ic(BatteryCharging, '#dc2626'),
  nobreak_dc:      ic(BatteryCharging, '#ea580c'),
  nobreak_ac:      ic(BatteryCharging, '#dc2626'),
  bateria_ext:     ic(Battery, '#eab308'),
  modulo_bat:      ic(Battery, '#9333ea'),
  fonte:           ic(Plug, '#eab308'),
  quadro:          ic(LayoutGrid, '#374151'),
  quadro_eletrico: ic(LayoutGrid, '#6b7280'),
  cabo_engate:     ic(Unplug, '#dc2626'),
  borne_sak:       ic(GripHorizontal, '#78716c'),
  tomada:          ic(Plug, '#6b7280'),
  ponto_dados:     ic(Waypoints, '#0ea5e9'),
  cx_passagem:     ic(Box, '#78716c'),
  // Alarme / Incendio
  alarme_central:   ic(ShieldAlert, '#ef4444'),
  sensor_presenca:  ic(PersonStanding, '#ef4444'),
  sensor_abertura:  ic(DoorOpen, '#ef4444'),
  sensor_barreira:  ic(ScanLine, '#ef4444'),
  sirene:           ic(Siren, '#ef4444'),
  teclado_alarme:   ic(Keyboard, '#ef4444'),
  detector_fumaca:  ic(Flame, '#991b1b'),
  acionador_manual: ic(CircleAlert, '#991b1b'),
  eletrificador:    ic(Zap, '#ef4444'),
  modulo_incendio:  ic(Flame, '#991b1b'),
  luminaria_emerg:  ic(Lightbulb, '#be123c'),
  // Comunicacao
  controle_remoto: ic(Radio, '#ef4444'),
  comunicador:     ic(Radio, '#ef4444'),
  receptor_rf:     ic(Signal, '#ef4444'),
  // Acessórios / Periféricos
  monitor_led:   ic(Monitor, '#2563eb'),
  botoeira_painel: ic(Grid2x2, '#8b5cf6'),
  mouse:         ic(Mouse, '#6b7280'),
  cabo_hdmi:     ic(Cable, '#374151'),
  cabo_usb:      ic(Usb, '#6b7280'),
  fechadura_mec: ic(Lock, '#ea580c'),
  fechadura_sol: ic(Lock, '#dc2626'),
  // Extra — banco de ícones para equipamentos custom
  monitor:     ic(Monitor, '#6b7280'),
  cpu:         ic(Cpu, '#6b7280'),
  mic:         ic(Mic, '#6b7280'),
  speaker:     ic(Speaker, '#6b7280'),
  bell:        ic(Bell, '#6b7280'),
  shield:      ic(Shield, '#6b7280'),
  scan:        ic(Scan, '#6b7280'),
  tv:          ic(Tv, '#6b7280'),
  power:       ic(Power, '#6b7280'),
  activity:    ic(Activity, '#6b7280'),
  gauge:       ic(Gauge, '#6b7280'),
  globe:       ic(Globe, '#6b7280'),
  building:    ic(Building2, '#6b7280'),
  key:         ic(Key, '#6b7280'),
  smartphone:  ic(Smartphone, '#6b7280'),
  truck:       ic(Truck, '#6b7280'),
  map_pin:     ic(MapPin, '#6b7280'),
  thermometer: ic(Thermometer, '#6b7280'),
  droplets:    ic(Droplets, '#6b7280'),
  wind:        ic(Wind, '#6b7280'),
  volume:      ic(Volume2, '#6b7280'),
  alert:       ic(AlertTriangle, '#6b7280'),
  move:        ic(Move, '#6b7280'),
  stack:       ic(SquareStack, '#6b7280'),
  box:         ic(Box, '#6b7280'),
  hash:        ic(Hash, '#6b7280'),
  toggle:      ic(ToggleLeft, '#6b7280'),
  compass:     ic(Compass, '#6b7280'),
  aperture:    ic(Aperture, '#6b7280'),
  focus:       ic(Focus, '#6b7280'),
  target:      ic(Target, '#6b7280'),
  megaphone:   ic(Megaphone, '#6b7280'),
  waypoints:   ic(Waypoints, '#6b7280'),
  audio_lines: ic(AudioLines, '#6b7280'),
}

// ── Banco de ícones para seleção no repositório de equipamentos ──
export const ICON_BANK = [
  { id: 'cam_dome', label: 'Câmera Dome' },
  { id: 'cam_bullet', label: 'Câmera Bullet' },
  { id: 'cam_ptz', label: 'Câmera PTZ' },
  { id: 'cam_fisheye', label: 'Fisheye' },
  { id: 'cam_lpr', label: 'LPR/Veicular' },
  { id: 'cam_wifi', label: 'Câmera WiFi' },
  { id: 'leitor_facial', label: 'Leitor Facial' },
  { id: 'controladora', label: 'Controladora' },
  { id: 'fechadura', label: 'Fechadura' },
  { id: 'motor', label: 'Motor' },
  { id: 'leitor_tag', label: 'Leitor Tag' },
  { id: 'sw_poe', label: 'Switch PoE' },
  { id: 'sw_normal', label: 'Switch' },
  { id: 'nvr', label: 'NVR/DVR' },
  { id: 'router', label: 'Roteador' },
  { id: 'ap_wifi', label: 'WiFi/AP' },
  { id: 'dio', label: 'DIO/Fibra' },
  { id: 'rack', label: 'Rack/Servidor' },
  { id: 'nobreak', label: 'Nobreak' },
  { id: 'bateria_ext', label: 'Bateria' },
  { id: 'fonte', label: 'Fonte/Plug' },
  { id: 'quadro', label: 'Quadro' },
  { id: 'alarme_central', label: 'Central Alarme' },
  { id: 'sensor_presenca', label: 'Presença' },
  { id: 'sensor_abertura', label: 'Abertura' },
  { id: 'sensor_barreira', label: 'Barreira' },
  { id: 'sirene', label: 'Sirene' },
  { id: 'detector_fumaca', label: 'Detector' },
  { id: 'eletrificador', label: 'Eletrificador' },
  { id: 'controle_remoto', label: 'Controle' },
  { id: 'monitor_led', label: 'Monitor LED' },
  { id: 'botoeira_painel', label: 'Painel Botoeira' },
  { id: 'mouse', label: 'Mouse' },
  { id: 'cabo_hdmi', label: 'Cabo HDMI' },
  { id: 'cabo_usb', label: 'Cabo USB' },
  { id: 'fechadura_mec', label: 'Fechadura Mec.' },
  { id: 'fechadura_sol', label: 'Fechadura Sol.' },
  { id: 'ponto_dados', label: 'Ponto de Dados' },
  { id: 'cx_passagem', label: 'Caixa Passagem' },
  // Extra icons
  { id: 'monitor', label: 'Monitor' },
  { id: 'cpu', label: 'CPU/Processador' },
  { id: 'mic', label: 'Microfone' },
  { id: 'speaker', label: 'Alto-falante' },
  { id: 'bell', label: 'Campainha' },
  { id: 'shield', label: 'Escudo' },
  { id: 'scan', label: 'Scanner' },
  { id: 'tv', label: 'TV/Display' },
  { id: 'power', label: 'Energia' },
  { id: 'activity', label: 'Atividade' },
  { id: 'gauge', label: 'Medidor' },
  { id: 'globe', label: 'Internet' },
  { id: 'building', label: 'Prédio' },
  { id: 'key', label: 'Chave' },
  { id: 'smartphone', label: 'Celular' },
  { id: 'thermometer', label: 'Temperatura' },
  { id: 'droplets', label: 'Umidade/Água' },
  { id: 'wind', label: 'Vento/HVAC' },
  { id: 'volume', label: 'Áudio' },
  { id: 'alert', label: 'Alerta' },
  { id: 'target', label: 'Alvo' },
  { id: 'waypoints', label: 'Topologia' },
  { id: 'box', label: 'Caixa' },
  { id: 'toggle', label: 'Toggle/Chave' },
  { id: 'focus', label: 'Foco' },
]

// ── Paleta de cores para equipamentos custom ──
export const COLOR_PALETTE = [
  '#f59e0b', '#ef4444', '#3b82f6', '#8b5cf6', '#059669',
  '#06b6d4', '#ec4899', '#84cc16', '#dc2626', '#2563eb',
  '#ea580c', '#0ea5e9', '#a855f7', '#14b8a6', '#f97316',
  '#6366f1', '#10b981', '#e11d48', '#0891b2', '#7c3aed',
  '#d97706', '#6b7280', '#374151', '#78716c', '#991b1b',
]
